In [1]:
import pandas as pd
import numpy as np
df1=pd.read_csv('F:/project/tmdb_5000_credits.csv')
df2=pd.read_csv('F:/project/tmdb_5000_movies.csv')

In [2]:
pwd

'C:\\Users\\HARSH VISHWAKARMA'

In [3]:
df1.columns = ['id','tittle','cast','crew']

In [4]:
df1.head()

,id,tittle,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
df2=df2.merge(df1,on='id')

In [6]:
df2.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,tittle,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
df2.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'tittle', 'cast', 'crew'],
      dtype='object')

In [8]:
df2['movie_title'] = df2['original_title'].str.lower()

In [9]:
# Parse the stringified features into their corresponding python objects

import ast
df2['genres'] = df2['genres'].map(lambda x: ast.literal_eval(x))
df2['cast'] = df2['cast'].map(lambda x: ast.literal_eval(x))
df2['crew'] = df2['crew'].map(lambda x: ast.literal_eval(x))

In [10]:

def make_genresList(x):
    genres = []
    st = " "
    for i in x:
        if i.get('name') == 'Science Fiction':
            scifi = 'Sci-Fi'
            genres.append(scifi)
        else:
            genres.append(i.get('name'))
    if genres == []:
        return np.NaN
    else:
        return (st.join(genres))

In [11]:
df2['genres']=df2['genres'].map(lambda x:make_genresList(x))

In [12]:
df2['genres']

0       Action Adventure Fantasy Sci-Fi
1              Adventure Fantasy Action
2                Action Adventure Crime
3           Action Crime Drama Thriller
4               Action Adventure Sci-Fi
                     ...
4798              Action Crime Thriller
4799                     Comedy Romance
4800      Comedy Drama Romance TV Movie
4801                                NaN
4802                        Documentary
Name: genres, Length: 4803, dtype: object

In [13]:

def get_actor1(x):
    casts = []
    for i in x:
       casts.append(i.get('name'))
        
    if casts == []:
        return np.NaN
    else:
        return (casts[0])

In [14]:
df2['actor_1_name'] = df2['cast'].map(lambda x: get_actor1(x))

In [15]:
def get_actor2(x):
    casts=[]
    for i in x:
        casts.append(i.get('name'))
    if casts ==[] or len(casts)<=1:
        return np.NaN
    else:
        return casts[1]

In [16]:
df2['actor_2_name'] = df2['cast'].map(lambda x: get_actor2(x))

In [17]:
def get_actor3(x):
    casts=[]
    for i in x:
        casts.append(i.get('name'))
    if casts ==[] or len(casts)<=2:
        return np.NaN
    else:
        return casts[2]

In [18]:
df2['actor_3_name'] = df2['cast'].map(lambda x: get_actor3(x))

In [19]:
def get_directors(x):
    directors=[]
    st=" "
    for i in x:
        if i.get('job')=='Director':
             directors.append(i.get('name'))
    if directors==[]:
        return np.NaN
    else:
        return st.join(directors)

In [20]:
df2['directors']=df2['crew'].map(lambda x: get_directors(x))

In [21]:
movie = df2.loc[:,['directors','actor_1_name','actor_2_name','actor_3_name','genres','title']]

In [22]:
movie

,directors,actor_1_name,actor_2_name,actor_3_name,genres,title
0,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Action Adventure Fantasy Sci-Fi,Avatar
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Keira Knightley,Adventure Fantasy Action,Pirates of the Caribbean: At World's End
2,Sam Mendes,Daniel Craig,Christoph Waltz,LÃ©a Seydoux,Action Adventure Crime,Spectre
3,Christopher Nolan,Christian Bale,Michael Caine,Gary Oldman,Action Crime Drama Thriller,The Dark Knight Rises
4,Andrew Stanton,Taylor Kitsch,Lynn Collins,Samantha Morton,Action Adventure Sci-Fi,John Carter
...,...,...,...,...,...,...
4798,Robert Rodriguez,Carlos Gallardo,Jaime de Hoyos,Peter Marquardt,Action Crime Thriller,El Mariachi
4799,Edward Burns,Edward Burns,Kerry BishÃ©,Marsha Dietlein,Comedy Romance,Newlyweds
4800,Scott Smith,Eric Mabius,Kristin Booth,Crystal Lowe,Comedy Drama Romance TV Movie,"Signed, Sealed, Delivered"
4801,Daniel Hsia,Daniel Henney,Eliza Coupe,Bill Paxton,NaN,Shanghai Calling
4802,Brian Herzlinger Jon Gunn Brett Winn,Drew Barrymore,Brian Herzlinger,Corey Feldman,Documentary,My Date with Drew

In [23]:
#drop null valued rows & columns
movie = movie.dropna(how='any')

In [24]:
movie.isna().sum()

directors       0
actor_1_name    0
actor_2_name    0
actor_3_name    0
genres          0
title           0
dtype: int64

In [25]:
movie['combines_crew']=movie['actor_1_name']+' '+movie['actor_2_name']+' '+movie['actor_3_name']+' '+movie['directors']+' '+movie['genres']

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [26]:
movie.to_csv('pre_processed_data.csv',index=False)

In [27]:
movie

,directors,actor_1_name,actor_2_name,actor_3_name,genres,title,combines_crew
0,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Action Adventure Fantasy Sci-Fi,Avatar,Sam Worthington Zoe Saldana Sigourney Weaver J...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Keira Knightley,Adventure Fantasy Action,Pirates of the Caribbean: At World's End,Johnny Depp Orlando Bloom Keira Knightley Gore...
2,Sam Mendes,Daniel Craig,Christoph Waltz,LÃ©a Seydoux,Action Adventure Crime,Spectre,Daniel Craig Christoph Waltz LÃ©a Seydoux Sam M...
3,Christopher Nolan,Christian Bale,Michael Caine,Gary Oldman,Action Crime Drama Thriller,The Dark Knight Rises,Christian Bale Michael Caine Gary Oldman Chris...
4,Andrew Stanton,Taylor Kitsch,Lynn Collins,Samantha Morton,Action Adventure Sci-Fi,John Carter,Taylor Kitsch Lynn Collins Samantha Morton And...
...,...,...,...,...,...,...,...
4796,Shane Carruth,Shane Carruth,David Sullivan,Casey Gooden,Sci-Fi Drama Thriller,Primer,Shane Carruth David Sullivan Casey Gooden Shan...
4798,Robert Rodriguez,Carlos Gallardo,Jaime de Hoyos,Peter Marquardt,Action Crime Thriller,El Mariachi,Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799,Edward Burns,Edward Burns,Kerry BishÃ©,Marsha Dietlein,Comedy Romance,Newlyweds,Edward Burns Kerry BishÃ© Marsha Dietlein Edwar...
4800,Scott Smith,Eric Mabius,Kristin Booth,Crystal Lowe,Comedy Drama Romance TV Movie,"Signed, Sealed, Delivered",Eric Mabius Kristin Booth Crystal Lowe Scott S...
4802,Brian Herzlinger Jon Gunn Brett Winn,Drew Barrymore,Brian Herzlinger,Corey Feldman,Documentary,My Date with Drew,Drew Barrymore Brian Herzlinger Corey Feldman ...

In [28]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2017"

df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [29]:
df2017=df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [30]:
df2017

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,6,Underworld: Blood Wars,Screen Gems / Lakeshore Entertainment / Sketch...,Anna Foerster (director); Cory Goodman (screen...,[2][3]
1,JANUARY,6,Arsenal,Lionsgate Premiere / Grindstone Entertainment ...,Steven C. Miller (director); Jason Mosberg (sc...,[4][5]
2,JANUARY,6,Between Us,IFC Films,Rafael Palacio Illingworth (director); Olivia ...,[6]
3,JANUARY,13,Monster Trucks,Paramount Pictures / Paramount Animation / Nic...,"Chris Wedge (director); Jonathan Aibel, Glenn ...",[7][8]
4,JANUARY,13,The Bye Bye Man,STX Entertainment / Intrepid Pictures,Stacy Title (director); Jonathan Penner (scree...,[9]
...,...,...,...,...,...,...
234,DECEMBER,22,Crooked House,Vertical Entertainment / Sony Pictures,Gilles Paquet-Brenner (director/screenplay); T...,[288]
235,DECEMBER,22,Hostiles,Entertainment Studios,Scott Cooper (director/screenplay); Donald E. ...,[289]
236,DECEMBER,25,All the Money in the World,TriStar Pictures,Ridley Scott (director); David Scarpa (screenp...,[290]
237,DECEMBER,25,Molly's Game,STX Entertainment,Aaron Sorkin (director/screenplay); Jessica Ch...,[291]
238,DECEMBER,25,Phantom Thread,Focus Features / Annapurna Pictures,Paul Thomas Anderson (director/screenplay); Da...,[292]

In [31]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"

df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [32]:
df2018=df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [33]:
import requests
import bs4 as bs
import urllib.request

In [34]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"

In [35]:
source = urllib.request.urlopen(link).read()
soup = bs.BeautifulSoup(source,'lxml')

In [36]:
tables = soup.find_all('table',class_='wikitable sortable')

In [37]:
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0]

In [38]:
df2019=df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [39]:
df2019

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,4,Escape Room,Columbia Pictures,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
236,DECEMBER,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[222]
237,DECEMBER,25,1917,Universal Pictures / DreamWorks Pictures / Ent...,Sam Mendes (director/screenplay); Krysty Wilso...,[223]
238,DECEMBER,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[224]
239,DECEMBER,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[225]
240,DECEMBER,27,Apparition,Vertical Pictures,Waymon Boone (director/screenplay); Mena Suvar...,[226]

In [40]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"

In [41]:
source = urllib.request.urlopen(link).read()
soup = bs.BeautifulSoup(source,'lxml')

In [42]:
tables = soup.find_all('table',class_='wikitable sortable')

In [43]:
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0]

In [44]:
df2020=df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [45]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '9917173c5dbf41760f72bee6cb239586'

In [46]:
from tmdbv3api import Movie
tmdb_movie=Movie() #inititalise constructor
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [47]:
df2017['genres'] = df2017['Title'].map(lambda x: get_genre(str(x)))

In [48]:
df2018['genres'] = df2018['Title'].map(lambda x: get_genre(str(x)))

In [49]:
df2019['genres'] = df2019['Title'].map(lambda x: get_genre(str(x)))

In [50]:
df2020['genres'] = df2020['Title'].map(lambda x: get_genre(str(x)))

In [51]:
df2020

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,genres
0,JANUARY,4,Escape Room,Columbia Pictures,"Adam Robitel (director); Bragi F. Schut, Maria...",[2],Thriller Action Mystery Horror
1,JANUARY,4,Rust Creek,IFC Films,Jen McGowan (director); Julie Lipson (screenpl...,[3],Thriller Drama
2,JANUARY,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4],Thriller
3,JANUARY,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5],Drama Adventure Family
4,JANUARY,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6],Comedy Drama
...,...,...,...,...,...,...,...
236,DECEMBER,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[222],Drama Romance
237,DECEMBER,25,1917,Universal Pictures / DreamWorks Pictures / Ent...,Sam Mendes (director/screenplay); Krysty Wilso...,[223],War Drama Action History
238,DECEMBER,25,Just Mercy,Warner Bros. Pictures / Participant Media,"Destin Daniel Cretton (director/screenplay), A...",[224],Drama Crime
239,DECEMBER,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[225],Drama
240,DECEMBER,27,Apparition,Vertical Pictures,Waymon Boone (director/screenplay); Mena Suvar...,[226],Horror Thriller

In [52]:
df2017=df2017[['Title','Cast and crew', 'genres']]

In [53]:
df2018=df2018[['Title','Cast and crew', 'genres']]

In [54]:
df2019=df2019[['Title','Cast and crew', 'genres']]

In [55]:
df2020=df2020[['Title','Cast and crew', 'genres']]

In [56]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [57]:
def get_actor1(x):
    return (x.split("screenplay); ")[-1]).split(", ")[0]

In [58]:
def get_actor2(x):
    if len(x.split("screenplay); ")[-1].split(", ")) < 2:
        return np.NaN
    else:
        return (x.split("screenplay); ")[-1]).split(", ")[1]

In [59]:
def get_actor3(x):
    if len(x.split("screenplay); ")[-1].split(", ")) < 3:
        return np.NaN
    else:
        return (x.split("screenplay); ")[-1]).split(", ")[2]

In [60]:
df2017['actor_1_name'] = df2017['Cast and crew'].map(lambda x: get_actor1(str(x)))
df2017['actor_2_name'] = df2017['Cast and crew'].map(lambda x: get_actor2(str(x)))
df2017['actor_3_name'] = df2017['Cast and crew'].map(lambda x: get_actor3(str(x)))
df2017['director'] = df2017['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [61]:
df2018['actor_1_name'] = df2018['Cast and crew'].map(lambda x: get_actor1(str(x)))
df2018['actor_2_name'] = df2018['Cast and crew'].map(lambda x: get_actor2(str(x)))
df2018['actor_3_name'] = df2018['Cast and crew'].map(lambda x: get_actor3(str(x)))
df2018['director'] = df2018['Cast and crew'].map(lambda x: get_director(str(x)))

In [62]:
df2019['actor_1_name'] = df2019['Cast and crew'].map(lambda x: get_actor1(str(x)))
df2019['actor_2_name'] = df2019['Cast and crew'].map(lambda x: get_actor2(str(x)))
df2019['actor_3_name'] = df2019['Cast and crew'].map(lambda x: get_actor3(str(x)))
df2019['director'] = df2019['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [63]:
df2020['actor_1_name'] = df2020['Cast and crew'].map(lambda x: get_actor1(str(x)))
df2020['actor_2_name'] = df2020['Cast and crew'].map(lambda x: get_actor2(str(x)))
df2020['actor_3_name'] = df2020['Cast and crew'].map(lambda x: get_actor3(str(x)))
df2020['director'] = df2020['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [64]:
df2017=df2017[['Title','actor_1_name','actor_2_name','actor_3_name','director', 'genres']]
df2018=df2018[['Title','actor_1_name','actor_2_name','actor_3_name','director', 'genres']]
df2019=df2019[['Title','actor_1_name','actor_2_name','actor_3_name','director', 'genres']]
df2020=df2020[['Title','actor_1_name','actor_2_name','actor_3_name','director', 'genres']]

In [65]:
movies=df2020.append(df2019.append(df2018.append(df2017,ignore_index=True),ignore_index=True),ignore_index=True)

In [66]:
movies['combined_crew']=movies['actor_1_name']+', '+movies['actor_2_name']+', '+movies['actor_3_name']+', '+movies['director']

In [67]:
movie['director']=movie['directors']

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [68]:
movie['combined_crew']=movie['combines_crew']

C:\Users\HARSH VISHWAKARMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [69]:
movies['title']=movies['Title']

In [70]:
movie=movie[['title','actor_1_name','actor_2_name','actor_3_name','director', 'genres','combined_crew']]

In [71]:
movie=movies.append(movie,ignore_index=True)

In [74]:
movie=movie[['title','actor_1_name','actor_2_name','actor_3_name','director', 'genres','combined_crew']]

In [76]:
movie.to_csv('main_data.csv',index=False)

In [77]:
movie

,title,actor_1_name,actor_2_name,actor_3_name,director,genres,combined_crew
0,Escape Room,Taylor Russell,Logan Miller,Deborah Ann Woll,Adam Robitel,Thriller Action Mystery Horror,"Taylor Russell, Logan Miller, Deborah Ann Woll..."
1,Rust Creek,Hermione Corfield,Jay Paulson,Sean O'Bryan,Jen McGowan,Thriller Drama,"Hermione Corfield, Jay Paulson, Sean O'Bryan, ..."
2,American Hangman,Donald Sutherland,Vincent Kartheiser,Oliver Dennis,Wilson Coneybeare,Thriller,"Donald Sutherland, Vincent Kartheiser, Oliver ..."
3,A Dog's Way Home,Bryce Dallas Howard,Edward James Olmos,Alexandra Shipp,Charles Martin Smith,Drama Adventure Family,"Bryce Dallas Howard, Edward James Olmos, Alexa..."
4,The Upside,Bryan Cranston,Kevin Hart,Nicole Kidman,Neil Burger,Comedy Drama,"Bryan Cranston, Kevin Hart, Nicole Kidman, Nei..."
...,...,...,...,...,...,...,...
5705,Primer,Shane Carruth,David Sullivan,Casey Gooden,Shane Carruth,Sci-Fi Drama Thriller,Shane Carruth David Sullivan Casey Gooden Shan...
5706,El Mariachi,Carlos Gallardo,Jaime de Hoyos,Peter Marquardt,Robert Rodriguez,Action Crime Thriller,Carlos Gallardo Jaime de Hoyos Peter Marquardt...
5707,Newlyweds,Edward Burns,Kerry BishÃ©,Marsha Dietlein,Edward Burns,Comedy Romance,Edward Burns Kerry BishÃ© Marsha Dietlein Edwar...
5708,"Signed, Sealed, Delivered",Eric Mabius,Kristin Booth,Crystal Lowe,Scott Smith,Comedy Drama Romance TV Movie,Eric Mabius Kristin Booth Crystal Lowe Scott S...
5709,My Date with Drew,Drew Barrymore,Brian Herzlinger,Corey Feldman,Brian Herzlinger Jon Gunn Brett Winn,Documentary,Drew Barrymore Brian Herzlinger Corey Feldman ...